# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDFABF
background         #14111B
cursor             #83B9AF

active_tab_foreground     #14111B
active_tab_background     #FDFABF
inactive_tab_foreground   #FDFABF
inactive_tab_background   #14111B

active_border_color   #FDFABF
inactive_border_color #14111B
bell_border_color     #55232F

color0      #3B3944
color1		#55232F
color2		#065977
color3		#BF3026
color4		#916B68
color5		#BE9C7F
color6		#BBB535
color7		#F4F09A
color8		#ABA86C
color9		#712E3F
color10		#08779F
color11		#FF4033
color12		#C18E8B
color13		#FDD0A9
color14		#FAF147
color15		#F4F09A
